### PR TITLE
Removed type with wrong units, used Real instead

### PR DESCRIPTION
**Pull request by casella**
See discussion in [OpenModelica's PR 240](https://github.com/OpenModelica/OpenModelica/pull/240)

### CODE REVIEW

**Comment by casella** [comment]
Made a PR to the wrong repository

**Comment by casella** [comment]
It was the right repository, after all...

**Comment by casella** [comment]
@rfranke are you ok with this change?

**Comment by rfranke** [comment]
@casella thank you for the fix!

**Pull request merged**
